# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'StoreRenewal' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
   pod 'SnapKit', '~> 5.0.0'
   pod 'Alamofire', '~> 5.0.0-rc.3'
   pod 'Kingfisher', '~> 5.0'
   pod 'lottie-ios'
   pod 'Swift_PageMenu', '~> 1.4'
   pod 'Tabman', '~> 2.9'

  # Pods for StoreRenewal

end
